### ISSUE TITLE
Incorrect/outdated instructions for repo

### ISSUE THREAD

**Issue by fNek** [seL4/sel4-tutorials#21]
The [repo manifest](https://github.com/SEL4PROJ/sel4-tutorials-manifest/) contains a distinction between seL4 and camkes tutorials. It appears to me that, at some point, this was done using differently named XML manifest files, but it is now done by putting the different manifests into separate branches.
However, at several points in the documentation, learners are instructed to select the manifest they want to check out by filename (which will no longer work and produce a fatal error).

The old instructions ask the user to execute the following command:

    repo init -u http://github.com/sel4proj/sel4-tutorials-manifest -m sel4-tutorials.xml

I believe that the correct command should be either:

    repo init -u http://github.com/sel4proj/sel4-tutorials-manifest -b sel4-tutorials

or:

    repo init -u http://github.com/sel4proj/sel4-tutorials-manifest

The first option seems more likely to me, but from looking at the manifest repository on GitHub, I am not sure which one is correct.

This includes, at least:

- The README of this repository
- The Wiki (pages "Getting Started", "Tutorials" and "seL4 Tutorial 1")
- The file "docs/seL4-APILib-details.pdf" in this repository

I am neither experienced in nor committed to this project enough to do this myself, but does somebody want to update this?

**Comment by kent-mcleod** [comment]
Hi.

Thanks for pointing this out.

We have changed the way that the manifests are updated in the sel4-tutorials-manifest repository, and the documentation hasn't been updated to reflect that.  The master branch was supposed to still be pointing at revision 6dc9be9c371584c9ff766f390062f3d4b37a5483 where the old documentation was still valid.  Until the documentation is updated I'll revert master back to that revision.  If you do want to use the newer manifests, then the new branches (camkes-tutorials, camkes-solutions, sel4-tutorials, sel4-solutions) each contain a default manifest (default.xml) that contains the most recent version of the libraries that passed all of our tests.  Additionally, the tagged revisions conatains the manifests for the most recently released versions.

If you want to close this issue once the master branch is fixed you can, otherwise I am happy keeping the issue open until all of the documentation is fixed also.

**Comment by HediDlp** [comment]
> Hi.
> 
> Thanks for pointing this out.
> 
> We have changed the way that the manifests are updated in the sel4-tutorials-manifest repository, and the documentation hasn't been updated to reflect that. The master branch was supposed to still be pointing at revision 6dc9be9c371584c9ff766f390062f3d4b37a5483 where the old documentation was still valid. Until the documentation is updated I'll revert master back to that revision. If you do want to use the newer manifests, then the new branches (camkes-tutorials, camkes-solutions, sel4-tutorials, sel4-solutions) each contain a default manifest (default.xml) that contains the most recent version of the libraries that passed all of our tests. Additionally, the tagged revisions conatains the manifests for the most recently released versions.
> 
> If you want to close this issue once the master branch is fixed you can, otherwise I am happy keeping the issue open until all of the documentation is fixed also.

Hi,
Thanks.
It would be really great help to update documentation.
I have trouble how to debug code. Which file/flages must be set?

I appreciated your help.

**Comment by axel-h** [comment]
Closing. Original problem is solved.
